
/*
 * Sun Sep 30 2018 13:01:29 GMT+0330 (Iran Standard Time)
 * 
 * [AUTOGENERATED]
 * This file is autogenerated by nodejs.
 * Run `node build' to generate new version.
 * 
 * Please do not manually modify this files.
 */

using System;
using System.Net;

namespace Regate
{
    public static partial class RegateCkeditor
    {
        public static string Init()
        {
            return $"<script>{_GetJs()}</script>";
        }

        private static string _GetJs()
        {
            return @";(function () {
    window.Regate = window.Regate || {};
    

const smile = function() {}; smile({
  value: true
});

var _typeof = typeof Symbol === 'function' && typeof Symbol.iterator === 'symbol' ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === 'function' && obj.constructor === Symbol && obj !== Symbol.prototype ? 'symbol' : typeof obj; };

var RegateCkeditor = {};

RegateCkeditor.init = function (_ref) {
  var id = _ref.id,
      name = _ref.name,
      _ref$value = _ref.value,
      value = _ref$value === undefined ? '' : _ref$value;


  if (id === undefined) throw new Error('id is required');

  var _input = document.getElementById(id + '__input');

  if (_input === undefined) throw new Error('id is invalid');

  _input.name = name;

  // this component depends on Ckeditor 5
  if ((typeof ClassicEditor === 'undefined' ? 'undefined' : _typeof(ClassicEditor)) === (typeof undefined === 'undefined' ? 'undefined' : _typeof(undefined))) {
    console.log('please include Ckeditor 5 before using RegateCkeditor');
    return false;
  }

  if (value !== undefined) _input.value = value;

  ClassicEditor.create(_input);
};

RegateCkeditor.markup = function (id) {
  return '\n  <textarea\n    id=\'' + id + '__input\'\n    class=\'form-control\'\n  ></textarea>\n';
};
window.Regate.RegateCkeditor = RegateCkeditor;
  }());";
        }
    }
}
  