
/*
 * Sun Sep 30 2018 13:23:29 GMT+0330 (Iran Standard Time)
 * 
 * [AUTOGENERATED]
 * This file is autogenerated by nodejs.
 * Run `node build' to generate new version.
 * 
 * Please do not manually modify this files.
 */

using System;
using System.Net;

namespace Regate
{
    public static partial class RegateContenteditable
    {
        public static string Init()
        {
            return $"<script>{_GetJs()}</script>";
        }

        private static string _GetJs()
        {
            return @";(function () {
    window.Regate = window.Regate || {};
    

var smile = function() {}; smile({
  value: true
});
var RegateContentEditable = {};

RegateContentEditable.init = function (_ref) {
  var id = _ref.id,
      name = _ref.name,
      _ref$value = _ref.value,
      value = _ref$value === undefined ? '' : _ref$value;


  if (id === undefined) throw new Error('id is required');

  var _input = document.getElementById(id + '__input');
  var _div = document.getElementById(id + '__div');

  if (_input === undefined) throw new Error('id is invalid');

  _input.name = name;

  if (value !== undefined) {
    _input.value = value;
    _div.innerHTML = value;
  }

  _div.oninput = function () {
    var html = _div.innerHTML;
    _input.value = html;
  };
};

RegateContentEditable.markup = function (id) {
  return '\n  <div>\n    <textarea\n      id=\'' + id + '__input\'\n      class=\'form-control\'\n      style=\'display: none;\'\n    ></textarea>\n    <div\n      class=\'form-control\'\n      style=\'height: auto !important\'\n      id=\'' + id + '__div\'\n      contenteditable=\'true\'\n    ></div>\n  </div>\n';
};
window.Regate.RegateContenteditable = RegateContentEditable;
  }());";
        }
    }
}
  